config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :sliders
  resources :posts
  resources :visitors do
  	member do
		get 'polling'
	end
end
  resources :dishes
  get "dania/:id" => "dishes#index", :as => :dishes_index

  resources :boxes
  resources :admins
  
  
root 'visitors#index'
get 'nowa-kategoria' => "dishes#add_category", :as => :new_type
get 'edytuj_kategorie/:id' => "dishes#edit_category", :as => :edit_category
delete 'usun_kategorie/:id' => "dishes#deletecategory", :as => :delete_category
post 'dodano-kategorie' => "dishes#newcategory"
patch 'zaaktualizowano-kategorie' => "dishes#updatecategory"
get 'zaaktualizowano-kategorie' => "dishes#updatecategory"
get 'rodzaj' => "dishes#index"

end

app/views/admins/_boxes.html.erb
<div id="boxes-controler">

	<div class="header">Jak maja wygladac 3 okna pod slajderem? Dodaj nowe: <%= link_to 'New Box', new_box_path %></div>
	
	<div>Opublikowane</div>
	
	<div id="boxes">

		<% @box_published.each do |box| %>

		<%= link_to post_url(box.artykul) do %>
			<div class="box-img" id="box-img<%= box.id %>"  style="background-image:url('<%= box.cover.url %>');">
				<div class="to-shadow">
		
					<div class="box-img-text">
						<%= link_to 'Edit', '#', class: "box-popup", id: box.id, remote: true %>
						<%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "delete_box" %>
						<div class="box-img-subtitle">
							<%= box.first_title %>
						</div>
			
						<div class="box-img-title">
							<%= box.second_title %>
						</div>
					
					</div>
				
				</div>
				<div id="pop-up" class="<%= box.id %>">
				<% @box = box %>
				<%= render "boxes/popup_form" %>
		</div>
		</div>
		<% end %>
		
	<% end %>
	</div>

	<div>Nie widoczne na stronie:</div>
	<div id="boxes">

		<% @box_unpublished.each do |box| %>

		<%= link_to post_url(box.artykul) do %>
			<div class="box-img" id="box-img<%= box.id %>"  style="background-image:url('<%= box.cover.url %>');">
				<div class="to-shadow">
		
					<div class="box-img-text">
						<%= link_to 'Edit', '#', class: "box-popup", id: box.id, remote: true %>
						<%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "delete_box" %>
						<div class="box-img-subtitle">
							<%= box.first_title %>
						</div>
			
						<div class="box-img-title">
							<%= box.second_title %>
						</div>
					
					</div>
				
				</div>
				<div id="pop-up" class="<%= box.id %>">
					<% @box = box %>
					<%= render "boxes/popup_form" %>
				</div>
		</div>
		<% end %>
		
	<% end %>
	</div>

</div>

<script type="text/javascript">
      $(function() {
		$('.box-popup').click(function() {
		$id = $(this).attr("id");
		});
       $( ".box-popup" ).on( "click", function() {
			$('div.'+$id).show();
		});
		$("div.close").click(function() {
			$off = $(this).attr("id");
			$('div#pop-up.'+$off).fadeOut();
		});
      });
 </script>

app/views/admins/_controls.html.erb
<div id="controls">

	<div id="inside-controls">
	
		<div class="icon">
			Edytuj Slidery
			<%= image_tag ("/system/controls/slider-icon.png") %>
		</div>

		<div class="icon">
			Edytuj Pudełka
			<%= image_tag ("/system/controls/box-icon.png") %>
		</div>
		
		<div class="icon">
			Edytuj Bloga
			<%= image_tag ("/system/controls/blog-icon.png") %>
		</div>
		
		<div class="icon">
			Edytuj Dania
			<%= image_tag ("/system/controls/dish-icon.png") %>
		</div>
		
	</div>
</div>

app/views/admins/_dishes.html.erb
<div id="dishes-controler">
	<div class="header">Zarządzaj oraz dodawaj nowe dania: <%= link_to 'New Dish', new_dish_path %></div>

		
		<div class="dishes-container">
		<% @dishes.each do |dish| %>
			<div class="pizza" id="pizza<%= dish.id %>" style="background-image:url('<%= dish.icon.url %>');">
		
				<div class="to-shadow">
			<div class="pizza-text">
				<div class="pizza-name">
					<%= dish.nazwa %>
				</div>
			
				<div class="pizza-ingredients">
					<%= dish.skladniki %>
					<%= link_to 'Show', dish %>
					<%= link_to 'Edit', "#",  id: dish.id, class: "dish-popup", remote: true %>
					<%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete_dish", remote: true %>
				</div>
			
			</div>
			
			</div>
			
			<div id="pop-up" class="dish<%= dish.id %>">
				<% @dish = dish %>
				<%= render "dishes/popup_form" %>
			</div>
			
		</div>
		
		<% end %>

	</div>

	<div id="list-categories">
	<h4>Kategorie Dań:</h4>
		<% @categories.each do |c| %>
		<div class="container" id="container<%= c.id %>">
			<div class="row">
				<%= c.rodzaj %>
			</div>
			<div class="large-2.columns">
				<% if c.visible == "Y" %>Opublikowane<% else %>Nieopublikowane <% end %>
			</div>
			<div class="large-2.columns">
				<%= link_to "Edytuj", edit_category_path(c.id) %>
				<%= link_to 'Usuń', delete_category_path(c.id), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "delete_category" %>
			</div>
		</div>
		<% end %>
	</div>
	<div id="add-category">
	<h2>Dodaj nową kategorię dań!</h2>
		<%= render "dishes/category_form" %>
	</div>
	
</div>





<script type="text/javascript">
      $(function() {
		$('.dish-popup').click(function() {
		$id = $(this).attr("id");
		});
       $( ".dish-popup" ).on( "click", function() {
			$('div.dish'+$id).show();
		});
		$("div.close").click(function() {
			$off = $(this).attr("id");
			$('div.dish'+$off).fadeOut();
		});
      });
 </script>

app/views/admins/_posts.html.erb
<div id="posts-controler">

<div id="header">Dodawaj, usuwaj, zarządzaj postami na stronie: <%= link_to 'New Post', new_post_path %></div>
<% @posts.each do |post| %>
<div class="post-container">
	<div class="post-cover">
		<%= image_tag post.cover.url %>
	</div>
	
	<div class="post-info">
		
		<div class="post-title">
			<%= post.tytul %>
		</div>
		
		<div class="post-category">
			Kategoria: Promocje
		</div>
		
		<div class="post-date">
			<%= link_to 'Show', post %></br>
			<%= link_to 'Edit', edit_post_path(post) %></br>
			<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
		</div>
		
	</div>
	
</div>
<% end %>

</div>

app/views/admins/_sliders.html.erb
<div id="slider-controler">
	<div class="header">Zarządzaj oraz dodawaj elementy do slidera: <%= link_to 'New Slider', new_slider_path %></div>
			
		<% @slider.each do |s| %>
			<div class="admin-panel-small" id="admin-panel-small<%= s.id %>">
				<div class="my-slider-box" style="background-image:url('<%= s.photo.url %>');">
				
					<div class="my-slider-buttons">
						<%= link_to 'Edit', '#', class: "slider-popup", id: s.id, remote: true %>
						<%= link_to 'Destroy', s, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_slider' %>

					</div>
					
					
					<div id="pop-up" class="<%= s.id %>">
					<% @slider = s %>
							<%= render "sliders/popup_form" %>
					</div>
					
					<div class="slider-titles">
					
						<div class="slider-title">
							<div class="link-inside">
								<%= s.tytul %>
							</div>
						</div>
						
						<div class="slider-subtitle">
							<div class="link-inside">
								<%= s.krotki_opis %>
							</div>
						</div>
							
					</div>
					
				</div>
				
			</div>
			
		<% end %>
</div>


		
<script type="text/javascript">
      $(function() {
		$('.slider-popup').click(function() {
		$id = $(this).attr("id");
		});
       $( ".slider-popup" ).on( "click", function() {
			$('div.'+$id).show();
		});
      });
 </script>

app/views/admins/index.html.erb
<div class="content">
	<H2>Witam w Panelu Administratora!</h2>
		
		<%= render "controls" %>
		
		<%= render "sliders" %>	
	
		<%= render "boxes" %>

		<%= render "posts" %>

		<%= render "dishes" %>

</div>