config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :sliders
  resources :posts
  resources :visitors do
  	member do
		get 'polling'
	end
end
  resources :dishes
  get "dania/:id" => "dishes#index", :as => :dishes_index

  resources :boxes
  resources :admins
  
  
root 'visitors#index'
get 'nowa-kategoria' => "dishes#add_category", :as => :new_type
get 'edytuj_kategorie/:id' => "dishes#edit_category", :as => :edit_category
delete 'usun_kategorie/:id' => "dishes#deletecategory", :as => :delete_category
post 'dodano-kategorie' => "dishes#newcategory"
patch 'zaaktualizowano-kategorie' => "dishes#updatecategory"
get 'zaaktualizowano-kategorie' => "dishes#updatecategory"
get 'rodzaj' => "dishes#index"

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

	def index
		@slider = Slider.all
		@box = Box.where(:published => "y").limit(3).order(:position)
		@promotions = Post.where(:is_promotion => "y").limit(3)
		@categories = Type.where(:visible => "y")
		session.delete(:storeid)
	end
	
	def polling
		@slider = Slider.all
		# @i needed to work left and right button
		@start ||= 0
		respond_to do |format|
			format.js
		end
	end

end

app/helpers/visitors_helper.rb
module VisitorsHelper


	
end

app/views/visitors/_content.html.erb
<div id="content-index">
	
	<div id="content-main">
		
		<div class="content-box">
			
			<div class="content-box-divider"></div>
			
			<div class="content-box-title">
				<b>Menu</b>
			</div>
			
			
			<div class="content-box-field">
				<ul>
					<% @categories.each do |c| %>
						<li><%= link_to c.rodzaj, dishes_index_url(c.rodzaj) %></li>
					<% end %>
				</ul>
			</div>
		
		</div>
		
		<div class="content-box">
		
			<div class="content-box-divider"></div>
			
			<div class="content-box-title">
				<b>Pizzeria Golomp</b>
			</div>
			
			<div class="content-box-field">
				<ul>
					<li>Doświadczenie</li>
					<li>O nas</li>
					<li>Kontakt</li>
				</ul>
			</div>
			
		</div>
		
		<div class="content-box">
		
			<div class="content-box-divider"></div>
		
			<div class="content-box-title">
				<b>Promocje:</b>
			</div>
			
			<div class="content-box-field">
				<ul>
				<% @promotions.each do |p| %>
					<li><%= link_to p.tytul, post_url(p.id) %></li>
				<% end %>
				</ul>
			</div>
			
		</div>
		
	</div>

</div>

app/views/visitors/_sidebar.html.erb
<div id="places">
	<div id="places-title">
		<b>Nasze placowki:</b>
	</div>
	
	<div id="places-content">
		<div class="address-city">Poznań - Rataje</div><div class="address-street">ul. Leśna 32</div>
		<div class="address-city">Poznań - Grunwald</div><div class="address-street">ul. Grunwaldzka 99</div>
		<div class="address-city">Poznań - Smochowice</div><div class="address-street">ul. Komornicza 2</div>
	</div>
</div>

app/views/visitors/_slider.html.erb
<% if defined?(locals[:id]) == nil %>
	<% $usable = 0 %>
<% else %>
	<% $usable = locals[:id] %>
<% end %>

<div class="my-slider-box" style="background-image:url('<%= @slider[$usable].photo.url %>');">
	
		<div class="my-slider-buttons">
		
		<%= link_to polling_visitor_url($usable - 1), remote: true do %>
			<div class="my-slider-button-left">
				<img src="http://iconshow.me/media/images/ui/ios7-icons/png/512/chevron-left.png">
			</div>
		<% end %>
		
		<%= link_to polling_visitor_url($usable + 1), remote: true do %>
			<div class="my-slider-button-right">
				<img src="http://image.flaticon.com/icons/svg/60/60758.svg">
			</div>
		<% end %>
		
		<div class="slider-titles">
		
				<div class="slider-title">
					<%= link_to post_url(@slider[$usable].artykul) do %>
						<div class="link-inside">
							<%= @slider[$usable].tytul %>
						</div>
					<% end %>
				</div>
			
				<div class="slider-subtitle">
					<%= link_to post_url(@slider[$usable].artykul) do %>
						<div class="link-inside">
							<%= @slider[$usable].krotki_opis %>
						</div>
					<% end %>
				</div>
				
		</div>
		
	</div>
</div>

app/views/visitors/index.html.erb
<div id="main-visitor">

<%= content_tag :div, class: "my-slider", data: {url:polling_visitor_url(9999)} do %>
	<%= render "slider" %>
<% end %>


<%= render "sidebar" %>

<%= render "boxes/boxes" %>

<%= render "content" %>
</div>

app/views/visitors/polling.js.erb
<%# $i is changed every 8 seconds and send as ID parameter, based on it we are changing slider images on page. $d is to make back button work %>
<% $length = @slider.size - 1 %>
<% session[:storeid] ||= 0 %>

<% if params[:id].to_i == 9999 %>
	
	<% if session[:storeid] >= $length %>
		<% session[:storeid] = 0 %>
	<% else %>
		<% session[:storeid] = session[:storeid] + 1 %>
	<% end %>
<% else %>
	
	<% if params[:id].to_i < 0 %>
		<% session[:storeid] = $length %>
	<% else %>
	
		<% if params[:id].to_i > $length %>
			<% session[:storeid] = 0 %>
		<% else %>
			<% session[:storeid] = params[:id].to_i %>
		<% end %>
		
	<% end %>
	
<% end %>

$('.my-slider').html('<%= j render 'visitors/slider', :locals => {:id => session[:storeid] } %>')
$('.my-slider-box').fadeTo(0, 0.0).fadeTo(1000, 1.0);
$('.my-slider-box').delay(6000).fadeTo(1000, 0.0);
SliderPoller.poll();	