config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :sliders
  resources :posts
  resources :visitors do
  	member do
		get 'polling'
	end
end
  resources :dishes
  get "dania/:id" => "dishes#index", :as => :dishes_index

  resources :boxes
  resources :admins
  
  
root 'visitors#index'
get 'nowa-kategoria' => "dishes#add_category", :as => :new_type
get 'edytuj_kategorie/:id' => "dishes#edit_category", :as => :edit_category
delete 'usun_kategorie/:id' => "dishes#deletecategory", :as => :delete_category
post 'dodano-kategorie' => "dishes#newcategory"
patch 'zaaktualizowano-kategorie' => "dishes#updatecategory"
get 'zaaktualizowano-kategorie' => "dishes#updatecategory"
get 'rodzaj' => "dishes#index"

end

app/models/box.rb
class Box < ActiveRecord::Base

  has_attached_file :cover, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
  
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]
  
  def index
    @box = Box.all
  end

  def show
  end

  def new
    @box = Box.new
  end

  # POST /sliders
  # POST /sliders.json
  def create
    @box = Box.new(box_params)
    respond_to do |format|
      if @box.save
        format.html { redirect_to params[:box][:prev_url], notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Slider was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
		format.js   { render :layout => false }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to sliders_url, notice: 'Slider was successfully destroyed.' }
      format.json { head :no_content }
	  format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:first_title, :second_title, :artykul, :cover, :published, :position)
    end
end

app/views/boxes/_admin.html.erb
<%= link_to post_url(@box.artykul) do %>
	<div class="box-img" id="box-img<%= @box.id %>"  style="background-image:url('<%= @box.cover.url %>');">
		<div class="to-shadow">
	
			<div class="box-img-text">
				<%= link_to 'Edit', '#', class: "box-popup", id: @box.id, remote: true %>
				<%= link_to 'Destroy', @box, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "delete_box" %>
				
					<div class="box-img-subtitle">
						<%= @box.first_title %>
					</div>
		
					<div class="box-img-title">
						<%= @box.second_title %>
					</div>
				
				</div>
			
			</div>
			
			<div id="pop-up" class="<%= @box.id %>">
				<% @box = @box %>
				<%= render "boxes/popup_form" %>
			</div>
			
	</div>
	
<% end %>

<script type="text/javascript">
      $(function() {
		$('.box-popup').click(function() {
		$id = $(this).attr("id");
		});
       $( ".box-popup" ).on( "click", function() {
			$('div.'+$id).show();
		});
		$("div.close").click(function() {
			$off = $(this).attr("id");
			$('div#pop-up.'+$off).fadeOut();
		});
      });
 </script>

app/views/boxes/_boxes.html.erb
<div id="boxes">

    <% @box.each do |box| %>

	<%= link_to post_url(box.artykul) do %>
		<div class="box-img"  style="background-image:url('<%= box.cover.url %>');">
		
			<div class="to-shadow">
	
				<div class="box-img-text">
		
					<div class="box-img-subtitle">
						<%= box.first_title %>
					</div>
		
					<div class="box-img-title">
						<%= box.second_title %>
					</div>
				
				</div>
			
			</div>
		
	</div>
<% end %>
    <% end %>

</div>

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this slider from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_title %><br>
    <%= f.text_area :first_title %>
  </div>
  <div class="field">
    <%= f.label :second_title %><br>
    <%= f.text_area :second_title %>
  </div>
  
  <div class="field">
    <%= f.label :artykul %><br>
    <%= f.collection_select(:artykul, Post.select(:tytul, :id), :id, :tytul) %>
  </div>
  
   <div class="field">
		<%= f.label :cover %><br>
		<%= f.file_field :cover %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/_popup_form.html.erb
<div class="close" id="<%= @box.id %>"><%= image_tag "http://www.i2symbol.com/images/myspace/symbols/heavy_multiplication_x_u2716_icon_256x256.png" %></div>
<%= form_for(@box, remote: true) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this slider from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_title %><br>
    <%= f.text_area :first_title %>
  </div>
  <div class="field">
    <%= f.label :second_title %><br>
    <%= f.text_area :second_title %>
  </div>
  
  <div class="field">
    <%= f.label :artykul %><br>
    <%= f.collection_select(:artykul, Post.select(:tytul, :id), :id, :tytul) %>
  </div>
  
   <div class="field">
		<%= f.label "Edytuj okładkę tutaj:" %><br>
		<%= link_to "Edytuj", edit_box_path(@box) %>
  </div>
  
    <div class="field">
		<%= f.label :published %><br>
		<%= f.check_box :published, {}, "y", "n" %>
	</div>
	
	<div class="field">
		<%= f.label :position %><br>
		<%= f.select(:position, [1,2,3,"none"]) %>
	</div>

  <div class="actions">
    <%= f.submit class: "box-button" %>
  </div>
  
<% end %>

<style>
.close {
width:25px;
height:25px;
float:right;
display:inline-block;
}
.close img {
width:100%;
height:100%;
}
</style>

app/views/boxes/destroy.js.erb
$('.delete_box').bind('ajax:success', function() {  
        $('#box-img<%= @box.id %>').fadeOut();
});  

app/views/boxes/edit.html.erb
<h1>Edit Box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sliders</h1>



<div id="boxes">

    <% @box.each do |box| %>

		<div class="box-img" style="background-image:url('<%= box.cover.url %>');">
	
			<div class="box-img-text">
		
				<div class="box-img-subtitle">
					<%= box.first_title %>
				</div>
		
				<div class="box-img-title">
					<%= box.second_title %>
					<%= link_to 'Show', box %>
					<%= link_to 'Edit', edit_box_path(box) %>
					<%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %>
				</div>
				
		</div>
		
</div>

      </tr>
    <% end %>

</div>
<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<h1>New Box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<div id="boxes">

	<div class="box-img" style="background-image:url('<%= @box.cover.url %>');">
	
		<div class="box-img-text">
		
			<div class="box-img-subtitle">
				<%= @box.first_title %>
			</div>
		
			<div class="box-img-title">
				<%= @box.second_title %>
			</div>
			
		</div>
		
	</div>
	
</div>


<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/update.js.erb
$(document).ready(function() {
	$(".box-button").click('ajax:success', function(){
		$('div#pop-up.<%= @box.id %>').fadeOut();
		$('#box-img<%= @box.id %>').replaceWith('<%= escape_javascript(render "boxes/admin") %>');
    }); 
});