config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :sliders
  resources :posts
  resources :visitors do
  	member do
		get 'polling'
	end
end
  resources :dishes
  get "dania/:id" => "dishes#index", :as => :dishes_index

  resources :boxes
  resources :admins
  
  
root 'visitors#index'
get 'nowa-kategoria' => "dishes#add_category", :as => :new_type
get 'edytuj_kategorie/:id' => "dishes#edit_category", :as => :edit_category
delete 'usun_kategorie/:id' => "dishes#deletecategory", :as => :delete_category
post 'dodano-kategorie' => "dishes#newcategory"
patch 'zaaktualizowano-kategorie' => "dishes#updatecategory"
get 'zaaktualizowano-kategorie' => "dishes#updatecategory"
get 'rodzaj' => "dishes#index"

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  has_attached_file :icon, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\z/
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  # GET /dishes
  # GET /dishes.json
  def index
	@category = Type.where(:rodzaj => params[:id]).first
    @dishes = Dish.where(:rodzaj => @category.id)
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)
    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @box, notice: 'Slider was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
		format.js   { render :layout => false }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
	  format.js   { render :layout => false }
    end
  end
  
  def add_category
	@category = Type.new
  end
  
  def edit_category
	@category = Type.find(params[:id])
  end

  def newcategory
	@category = Type.new(type_params)
		if @category.valid?
			@category.save
			flash[:notice] = "Dodano nową kategorię - #{@category.rodzaj}"
			redirect_to admins_path
		else
			respond_to.html { redirect_to new_type }
			respond_to.json { render json: @category.errors, status: :unprocessable_entity }
		end
  end
  
	def updatecategory
	@category = Type.find(params[:type][:id])
	 respond_to do |format|
		  if @category.update(type_params)
			format.html { redirect_to admins_path, notice: 'Dish was successfully updated.' }
			format.json { render :show, status: :ok, location: @dish }
		  else
			format.html { render :edit }
			format.json { render json: @dish.errors, status: :unprocessable_entity }
		  end
		end
	end
	
	def deletecategory
		@category = Type.find(params[:id])
	    @category.destroy
		respond_to do |format|
			format.html { redirect_to admins_path, notice: 'Category was successfully destroyed.' }
			format.json { head :no_content }
			format.js   { render :layout => false }
		end
	end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:nazwa, :skladniki, :rodzaj, :icon)
    end
	
	def type_params
      params.require(:type).permit(:rodzaj, :visible)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_admin.html.erb
<div class="pizza" id="pizza<%= @dish.id %>" style="background-image:url('<%= @dish.icon.url %>');">
		
				<div class="to-shadow">
			<div class="pizza-text">
				<div class="pizza-name">
					<%= @dish.nazwa %>
				</div>
			
				<div class="pizza-ingredients">
					<%= @dish.skladniki %>
					<%= link_to 'Show', @dish %>
					<%= link_to 'Edit', "#",  id: @dish.id, class: "dish-popup", remote: true %>
					<%= link_to 'Destroy', @dish, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete_dish", remote: true %>
				</div>
			
			</div>
			
			</div>
			
			<div id="pop-up" class="dish<%= @dish.id %>">
				<%= render "dishes/popup_form" %>
			</div>
			
		</div>

app/views/dishes/_category_form.html.erb
<%= form_for @category, url: {controller: "dishes", action: "newcategory"}, html: {multipart: true} do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %><br>
    <%= f.text_area :rodzaj %>
  </div>
  
  	<div class="field">
		<%= f.label :visible %><br>
		<%= f.check_box :visible, {}, "y", "n" %>
	</div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %><br>
    <%= f.text_area :nazwa %>
  </div>
  
  <div class="field">
    <%= f.label :skladniki %><br>
    <%= f.text_area :skladniki %>
  </div>
  
    <div class="field">
		<%= f.label :rodzaj %><br>
		<%= f.collection_select(:rodzaj, Type.select(:rodzaj, :id), :id, :rodzaj) %>
		<%= link_to "Dodaj nową kategorię", {controller: "dishes", action: "add_category"} %>
		<%= link_to 'Edytuj kategorie', edytuj_kategorie_url %>
	</div>
	
	<div class="field">
		<%= f.label "Zdjecie" %><br>
		<%= f.file_field :icon %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/_popup_form.html.erb
<div class="close" id="<%= @dish.id %>"><%= image_tag "http://www.i2symbol.com/images/myspace/symbols/heavy_multiplication_x_u2716_icon_256x256.png" %></div>
<%= form_for(@dish, remote: true) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :nazwa %><br>
    <%= f.text_area :nazwa %>
  </div>
  
  <div class="field">
    <%= f.label :skladniki %><br>
    <%= f.text_area :skladniki %>
  </div>
  
    <div class="field">
		<%= f.label :rodzaj %><br>
		<%= f.collection_select(:rodzaj, Type.select(:rodzaj, :id), :id, :rodzaj) %>
		<%= link_to "Dodaj nową kategorię", {controller: "dishes", action: "add_category"} %>
		<%= link_to 'Edytuj kategorie', edit_category_path(@dish.rodzaj) %>
	</div>
	
	<div class="field">
		<%= f.label "Zdjecie" %><br>
		<%= f.file_field :icon %>
	</div>
  <div class="actions">
    <%= f.submit class: "dish-button"%>
  </div>
<% end %>

app/views/dishes/add_category.html.erb
<%= form_for @category, url: {controller: "dishes", action: "newcategory"}, html: {multipart: true} do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %><br>
    <%= f.text_area :rodzaj %>
  </div>
  
  	<div class="field">
		<%= f.label :visible %><br>
		<%= f.check_box :visible, {}, "y", "n" %>
	</div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/deletecategory.js.erb
$('.delete_category').bind('ajax:success', function() {  
        $('#container<%= @category.id %>').fadeOut();
});  

app/views/dishes/destroy.js.erb
$('.delete_dish').bind('ajax:success', function() {  
        $('#pizza<%= @dish.id %>').fadeOut();
});  

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/edit_category.html.erb
<div class="edit_categories">
		<%= form_for @category, url: {controller: "dishes", action: "updatecategory"} do |f| %>
		  <% if @category.errors.any? %>
			<div id="error_explanation">
			  <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

			  <ul>
			  <% @category.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			  <% end %>
			  </ul>
			</div>
		  <% end %>

		  <%= f.hidden_field :id, :value => @category.id %>
		  
		  <div class="field">
			<%= f.label :nazwa %><br>
			<%= f.text_area :rodzaj %>
		  </div>
		  
		<div class="field">
			<%= f.label :visible %><br>
			<%= f.check_box :visible, {}, "y", "n" %>
		</div>
		  
	  <div class="actions">
		<%= f.submit %>
		 </div>
	<% end %>
</div>

app/views/dishes/index.html.erb
<div id="content">

	<div class="dish-banner">
		<p class="title">Dostępne <%= params[:kategoria] %>: </p>
	</div>
	
	<div class="dishes-container">
    <% @dishes.each do |dish| %>
		<div class="pizza" style="background-image:url('<%= dish.icon.url %>');">
	
			<div class="to-shadow">
		<div class="pizza-text">
			<div class="pizza-name">
				<%= dish.nazwa %>
			</div>
		
			<div class="pizza-ingredients">
				<%= dish.skladniki %>
				<%= link_to 'Show', dish %>
				<%= link_to 'Edit', edit_dish_path(dish) %>
				<%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>
		
		</div>
		
		</div>
	
	</div>
    <% end %>
	</div>

<%= link_to 'New Dish', new_dish_path %>
</div>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @dish.nazwa %>
</p>

<p>
  <strong>Skladniki:</strong>
  <%= @dish.skladniki %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/update.js.erb
$(document).ready(function() {
	$(".dish-button").click('ajax:success', function(){
		$('div#pop-up.dish<%= @dish.id %>').fadeOut();
		$('#pizza<%= @dish.id %>').replaceWith('<%= escape_javascript(render "dishes/admin") %>');
    }); 
});